
image: kmdemos/gitpod_elixir_starter:1

tasks:
  - name: Get dependencies and run tests
    init: mix deps.get
    command: mix test.interactive

vscode:
  extensions:
    - elixir-lsp.elixir-ls
    - pantajoe.vscode-elixir-credo
