
image: kmdemos/gitpod_elixir_starter:1

tasks:
  - name: Get dependencies
    init: mix deps.get
  - name: Run tests interactively
    command: mix test.interactive

vscode:
  extensions:
    - elixir-lsp.elixir-ls
    - pantajoe.vscode-elixir-credo
